### ISSUE TITLE
Make the short listing configurable?

### ISSUE THREAD

**Issue by erwin** [ayosec/autols#1]
On the hard coded summary of each folder (when you have more than `n` folders), it would be very cool to have the last `n` filenames in that folder that we're modified... Maybe something like:

```
--Updated today
  foo bar baz
--Updated this week
  alice bob charlie david
```

For example, I often `cd ~/Downloads`, only to grab the most recent file, but usually can't remember exactly what the filename was.

AutoLS is a new idea for me. Very cool!

**Comment by ayosec** [comment]
Hi @erwin!

> On the hard coded summary of each folder (when you have more than `n` folders), it would be very cool to have the last `n` filenames in that folder that we're modified... Maybe something like:

autols always executes an external program (usually `ls`) to show the list. When I wrote it in 2011 I needed a way to skip the `ls` for directories with a lot of files, because (if I remember correctly) I had some directories with thousands of files on a very slow disk.

What you want to do can be done with a script like this:

```bash
#!/bin/sh

echo --Updated today
find . -maxdepth 1 -ctime -1 -not -name . -exec ls --color -d {} +

echo
echo --Updated this week
find . -maxdepth 1 -ctime +1 -ctime -7 -not -name . -exec ls --color -d {} +
```

To show the contents automatically, you can add something like this in `.bashrc`:

```bash
launch_autols() {
  if [ "$AUTOLS_LAST_DIR" = "$PWD" ]
  then
    return
  fi

  AUTOLS_LAST_DIR=$PWD

  if [ "$PWD" = "$HOME/Downloads" ]
  then
    # The script above
  else
    autols
  fi
}

AUTOLS_LAST_DIR=$PWD
PROMPT_COMMAND+="launch_autols;"
```


---

Last year I stopped using autols, and replaced it with [summer](https://github.com/ayosec/summer). It is the same idea (show contents when the current directory is changed), but it is *much* more powerful. Unfortunately, it is poorly documented, so it is still not very usable for others. I need to get some time to document it properly.

As an example, you can show a *Downloads* directory with a configuration like this:

```yaml
colors:
  column_label: ul cyan
  more_entries: "italic #444444"
  name_ellipsis: red
  disk_usage: "#442299"

columns:
  - matchers: [ type: directory ]
    label: Directories
    sort: deep_mtime desc
    max_name_width: 10

  - label: 1 day
    sort: deep_mtime desc
    matchers: [ all: [ type: file, changes: 1 day ] ]

  - label: 7 days
    sort: deep_mtime desc
    matchers: [ all: [ type: file, changes: 7 days ] ]

  - label: 30 days
    sort: deep_mtime desc
    matchers: [ all: [ type: file, changes: 30 days ] ]

  - label: 90 days
    max_name_width: 15
    sort: deep_mtime desc
    matchers: [ all: [ type: file, changes: 90 days ] ]

  - matchers: [ any ]
    include_hidden: true

collector:
  timeout: 200ms
  git_diff: false

grid:
  max_rows: 20
  max_name_width: 18

info:
  right:
    color: "normal #f0f0ff"
    text: "\n  %C{#9900ff}%p%C{black} - %C{cyan}%V{dirs}%C{black} dirs  \n"

  variables:
    dirs: [ type: directory ]
```

If you install summer, and invoke it with `summer -c config.yaml ~/Downloads` you should see the files in multiple columns, organized by their age.
